import { inject } from '@angular/core';
import { ActivatedRouteSnapshot, ResolveFn } from '@angular/router';
import { Member } from '../_models/member';
import { MembersService } from '../_services/members.service';

/**
 * Created with command:
 * ```
 * ng g resolver _resolvers/member-detailed --skip-tests
 * ```
 */
export const memberDetailedResolver: ResolveFn<Member> = (route: ActivatedRouteSnapshot) => {
  return inject(MembersService).getMember(route.paramMap.get('username')!)
}

// The below structure was generated by the Angular component template, but is
// not compatible with this Udemy course.
// @Injectable({
//   providedIn: 'root'
// })
// export class MemberDetailedResolver implements Resolve<Member> {

//   resolve(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): Observable<Member> {
//     const memberService = inject(MembersService);

//     return memberService.getMember(route.paramMap.get('username')!)
//   }
// }
